# environment
name: myenv
channels:
  - districtdatalabs
  - simpleitk
  - bioconda
  - conda-forge/label/cf202003
  - intel
  - sebp
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - keras=2.3.1
  - jupyter=1.0.0
  - matplotlib=3.3.4
  - medpy=0.4.0
  - nibabel=3.2.1
  - numpy=1.19.2
  - opencv=3.3.1
  - pandas=1.1.3
  - pydicom=1.2.0
  - pydot=1.4.1
  - python=3.6.13
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scikit-survival=0.14.0
  - scipy=1.5.2
  - seaborn=0.11.1
  - simpleitk=2.0.2
  - tensorboard=2.4.0
  - tensorflow=2.1.0
  - tensorflow-gpu=2.1.0
  - tqdm=4.28.1
  - xlrd=1.2.0
  - zipp=3.4.1
  - typing






  

